name: CI/CD Frontend Despachos

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-frontend:latest
          build-args: |
            VITE_API_DESPACHOS=${{ secrets.VITE_API_DESPACHOS }}
            VITE_API_VENTAS=${{ secrets.VITE_API_VENTAS }}

      - name: Deploy en EC2 Frontend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_FRONTEND_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-frontend:latest
            docker stop frontend-despachos || true
            docker rm frontend-despachos || true
            docker run -d \
              --name frontend-despachos \
              --restart always \
              -p 80:80 \
              ${{ secrets.DOCKERHUB_USERNAME }}/innovatech-frontend:latest
